# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPSb3QBSJ-s-9ShLaQrvbJtTGm96pn8x
"""

import streamlit as st

st.title("Hello Streamlit 👋")
st.write("This is a simple app!")

import streamlit as st
import pickle

st.title("🚗 Car Price Predictor using .pkl")

# Load trained model from pkl file
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Input from user
st.header("Enter Car Details")
car_id = st.number_input("Car ID", value=1)
brand = st.number_input("Brand (Encoded)", value=1)
year = st.number_input("Year", value=2020)
engine_size = st.number_input("Engine Size", value=2.0)
fuel = st.number_input("Fuel Type (Encoded)", value=1)
trans = st.number_input("Transmission (Encoded)", value=1)
mileage = st.number_input("Mileage", value=50000)
model_code = st.number_input("Model (Encoded)", value=1)

# Prediction
if st.button("Predict Price"):
    data = [[car_id, brand, year, engine_size, fuel, trans, mileage, model_code]]
    price = model.predict(data)[0]
    st.success(f"Predicted Price: ₹{price:,.2f}")