# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPSb3QBSJ-s-9ShLaQrvbJtTGm96pn8x
"""

import streamlit as st

st.title("Hello Streamlit 👋")
st.write("This is a simple app!")

import streamlit as st
import pickle

st.title("🚗 Car Price Predictor using .pkl")

# Load trained model from pkl file
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Input from user
st.header("Enter Car Details")
car_id = st.number_input("Car ID", value=1)
brand = st.number_input("Brand (Encoded)", value=1)
year = st.number_input("Year", value=2020)
engine_size = st.number_input("Engine Size", value=2.0)
fuel = st.number_input("Fuel Type (Encoded)", value=1)
trans = st.number_input("Transmission (Encoded)", value=1)
mileage = st.number_input("Mileage", value=50000)
model_code = st.number_input("Model (Encoded)", value=1)

# Prediction
if st.button("Predict Price"):
    data = [[car_id, brand, year, engine_size, fuel, trans, mileage, model_code]]
    price = model.predict(data)[0]
    st.success(f"Predicted Price: ₹{price:,.2f}")

st.write("Model expects features:", model.n_features_in_)

X = [['Car ID', 'brand_new', 'Year', 'Engine Size', 'fuel_new', 'trans_new', 'Mileage', 'mod_new']]

input_data = [[
    car_id,           # Car ID
    brand,            # Brand (encoded) - Changed from brand_encoded
    year,             # Year
    engine_size,      # Engine Size       # Model (encoded) - Changed from model_encoded
]]

# Debug line
st.write("Input shape:", len(input_data[0]))
st.write("Model expects:", model.n_features_in_)

price = model.predict(input_data)[0]
st.success(f"Predicted Car Price: ₹{price:,.2f}")

import numpy as np
input_array = np.array(input_data)
st.write("Final input shape:", input_array.shape)